services:
  kafka: 
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka
    ports: 
      - "9092:9092"
    environment:
    # This is kafka's built in system to manage it's own metadata and to manage cluster coordination internaly 
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller 
      # This define what brokers are controlers and can vote in imp cluster decisions 
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # If we set the replication factor to 1 the kafka metadata that keeps track of each messages the consumer has read 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # default is 3 
      # specifies the network interface and ports on which the broker is listens or incomming connections from clients nd other brokers 
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093
      # defines the addresses that kafka tells clients/brokers to connect to 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 

      # tells kafka where to store all of it's data fies, broker logs, controller metadata 
      KAFKA_LOG_DIRS: /tmp/kraft-combined-log 
    volumes:
      - kafka-kraft:/var/lib/kafka/data
volumes: 
  kafka-kraft: